### ISSUE TITLE
Building the project did not eliminate the red wavy lines

### ISSUE THREAD

**Issue by CNGoSeI** [boocs/unreal-clangd#10]
**VERSION:**
UE 5.3
LLVM 17.0.6

![Z5)H( {4FEYQA A408MCPOB](https://github.com/boocs/unreal-clangd/assets/97931796/13e35614-5772-4f75-bf74-8b0c0da34108)
![image](https://github.com/boocs/unreal-clangd/assets/97931796/338cc341-25b4-4d3a-a063-aa7b84b7c093)

Neither running the project in Debug nor building with Run Build Tasks eliminates the error message.

**Comment by boocs** [comment]
Two things to try:

1. I'm tracking a bug where Intellisense files get overwritten when building causing red squiggles. Try running my extensions command 'Update Compile Commands file` after you build. Should be fixed in next update.

    ![image](https://github.com/boocs/unreal-clangd/assets/62588629/d4d7e948-6b67-4e67-a461-ff62fd706814)

2. Could be the LLVM version. For UE 5.3, try LLVM 16.0.6.

**Comment by CNGoSeI** [comment]
> 有两件事要尝试：
> 
> 1. 我正在跟踪一个错误，该错误在构建时会导致智能感知文件被覆盖，从而导致红色波浪线。构建后尝试运行我的扩展命令“更新编译命令文件”。应该会在下次更新中修复。
>    ![图像](https://private-user-images.githubusercontent.com/62588629/296510930-d4d7e948-6b67-4e67-a461-ff62fd706814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTUzNTEsIm5iZiI6MTcwNTIxNTA1MSwicGF0aCI6Ii82MjU4ODYyOS8yOTY1MTA5MzAtZDRkN2U5NDgtNmI2Ny00ZTY3LWE0NjEtZmY2MmZkNzA2ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA2NTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTU0NGQzZDE3NDkzMmYxMWVkYTkwNjVmNWRlM2U1Y2E4MzM5NmJkNTE3NjdiMDc3OTA3YTJkNmU1MTVlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PAbGLA8C5fM6CcwJH1z9-34pFwyDENTF1aDIsfyMMrk)
> 2. 可能是 LLVM 版本。对于 UE 5.3，请尝试 LLVM 16.0.6。

Problems with LLVM version, now it works!
