### ISSUE TITLE
`** Error **: No response paths found in compile commands with regex: (?<=@\\*\"*)[\w/][\w:\\\s./]+.gcd` (+ more)

### ISSUE THREAD

**Issue by maikkundev** [boocs/unreal-clangd#13]
I'm getting a few errors each time I try to create a clang project:

1. `** Error **: Couldn't find a Source folder compile commands entry for completionHelper to use!`
2. `** Error **: No response paths found in compile commands with regex: (?<=@\\*\"*)[\w/][\w:\\\s./]+.gcd`
3. `** Error **: Couldn't create response files!`

Also, the plugin asks me twice if I want to generate IntelliSense files.

Here's the whole output:
```
Started unreal clangd 2.3.0

Startup Intellisense check is disabled.

Warning: Couldn't set up New Source File Detection, compile commands doesn't exist yet.
Auto Parameter Hints was set to needed
Delegate Function Completions Fix was set to true
Auto Include Source Files Only was set to true
Running command create Unreal/Clangd project...

Found Unreal Version: 5.4.1

*** Running command to update compile commands file... ***

No need to delete uri. It doesn't exist: c:\Program Files\Epic Games\UE_5.4\compile_commands.json
Creating compile commands file in: c:\Program Files\Epic Games\UE_5.4

*** End updating compile commands file! ***

Attempting to copy compile commands file to: d:\Unreal\pewTest\.vscode\unreal-clangd\compile_commands.json
Copy successful!


** Error **: Couldn't find a Source folder compile commands entry for completionHelper to use!
Once you add files to your project's Source folder the above error will correct itself.
Response file quote fix is enabled. Attempting fix...
*** Fixing response files with quotes around paths...***

Getting response files from: d:\Unreal\pewTest\.vscode\unreal-clangd\compile_commands.json

** Error **: No response paths found in compile commands with regex: (?<=@\\*\"*)[\w/][\w:\\\s./]+.gcd

** Error **: Couldn't create response files!
Setting up new Source file detection...

Running command create Unreal/Clangd project...

Found Unreal Version: 5.4.1

End Task: unreal-clangd: Update Compile Commands
*** Running command to update compile commands file... ***

Successfully deleted: c:\Program Files\Epic Games\UE_5.4\compile_commands.json
Creating compile commands file in: c:\Program Files\Epic Games\UE_5.4

*** End updating compile commands file! ***

Attempting to ```
copy compile commands file to: d:\Unreal\pewTest\.vscode\unreal-clangd\compile_commands.json
Copy successful!

Completion helper file already exists. Will not overwrite.

** Error **: Couldn't find a Source folder compile commands entry for completionHelper to use!
Once you add files to your project's Source folder the above error will correct itself.
Response file quote fix is enabled. Attempting fix...
*** Fixing response files with quotes around paths...***

Getting response files from: d:\Unreal\pewTest\.vscode\unreal-clangd\compile_commands.json

** Error **: No response paths found in compile commands with regex: (?<=@\\*\"*)[\w/][\w:\\\s./]+.gcd

** Error **: Couldn't create response files!
End Task: unreal-clangd: Update Compile Commands
```

**Comment by boocs** [comment]
Weird, didn't get notification email till today...

Yeah, I haven't released 5.4 support yet because I had to redo how I did the extension. I had to pivot toward supporting native Intellisense files instead of using the Unreal Build Tool flag -mode=GenerateClangDataBase.

It's close. Should be out early this week!

**Comment by maikkundev** [comment]
I'd like to add that I tried again with 5.3.0 (angelscript branch) and I'm getting 'CoreMinimal.h' file not found. Is it because I'm using a different branch or am I doing something wrong?

**Comment by boocs** [comment]
Maybe! 

What OS do you run? If this new release doesn't work I might be able to download the angelscript branch and test it.  I can test Windows and Linux(ubuntu).

The new release is delayed a little but is very close.

**Comment by maikkundev** [comment]
I'm on Windows 11.
You'll have to compile the engine yourself if you want to test the AS branch on Linux AFAIK. 
They provide compiled binaries for Windows though!

**Comment by boocs** [comment]
I've released v2.5.0. 

You'll need to Create Project again and choose Full so new settings will overwrite old settings. You shouldn't have to uninstall.

Let me know if it works!

**Comment by boocs** [comment]
Yeah if clangd sees a .clang-tidy file it will be enabled. 

Unreal and linters are dangerous since Unreal does unconventional stuff. You really have to know what you're doing when using it. That's why I have it off by default during creation.

So does the normal code completion and other stuff work though with no errors?

**Comment by maikkundev** [comment]
Yup, works great!
