### ISSUE TITLE
still encounter numbers of error after clang installation

### ISSUE THREAD

**Issue by as3mbus** [boocs/unreal-clangd#4]
after installing and completing clang indexing, it still encounters several errors caused by several factors, including Unreal, and maybe my machine.

here are some : 
1. Complier and STL Version Mismatch
   ```cpp
   #if __clang_major__ < 16
   _EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 16.0.0 or newer.");
   #endif // ^^^ old Clang ^^^
   ```
2. A type specifier is required for all declarationsclang(missing_type_specifier) on `GENERATED_BODY` macro

some information would be appreciated

Great Visual Studio Plugin it is way faster than C++ intellisense

**Comment by boocs** [comment]
Which OS are  you running?

Certain clang/clangd versions are required for different Unreal versions. With Unreal 5.3 you need clang/clangd 16.0.6

**Comment by as3mbus** [comment]
i used unreal 5.2 installed build. 

and i've followed the documentation you provided by installing clang version for 5.2 which should be 15.0.1

i've tried to trace this and found that the code is located within MSVC build tool

**Comment by boocs** [comment]
It's late and forgot your first post. Weird that it said that about needing clang 16.0.0 or newer.  What file is saying that? Maybe you updated something you shouldn't have?

**Comment by boocs** [comment]
I'll try pulling up my 5.2 project tomorrow and try to extract everything it's using. It might be late though.

**Comment by as3mbus** [comment]
the file that produces error are in this path :

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\INCLUDE\yvals_core.h

is the `14.37` also the version you asked ?

sorry, i'm still not understand regarding building tool.

**Comment by boocs** [comment]
Install this instead of what you're using now:

1. Go here https://visualstudio.microsoft.com/downloads/
2. Then download and install this:

![image](https://github.com/boocs/unreal-clangd/assets/62588629/31aabbc9-ec46-4d81-8cff-1aba24731bd7)

3. When you're done you'll have to Refresh your project. Right click on  your .uproject file and go to 'Show more optiions" and choose 'Generate Visual Studio Project files'

![image](https://github.com/boocs/unreal-clangd/assets/62588629/074523e3-69f5-498e-a3b2-98a9a7b8611d)

4. This will overwrite your clangd project settings inside your workspace config so you'll need to reinstall your clangd project. 
Go here for instructions: https://github.com/boocs/unreal-clangd/tree/v2#reinstall-without-overwrite

**Comment by boocs** [comment]
I just realized I'm using an old version of Build Tools 2022 so I'm upgrading my version just to test and make sure it works.

**Comment by boocs** [comment]
After updating my Visual Build Tools 2022 I'm also getting problems now with yvals_core.h.

Thanks for the report, I'll try to see if this is fixable!

**Comment by boocs** [comment]
Ok Build Tools lets you install older versions of 2022.

After you install Build Tools 2022 open the visual studio installer and choose modify:
![image](https://github.com/boocs/unreal-clangd/assets/62588629/bfdb9975-a523-4622-8e75-d8df8db1273f)

Choose 'Individual components' and install MSVC 2022 build tools v143 v14.34 :
![image](https://github.com/boocs/unreal-clangd/assets/62588629/437ccefd-f559-41af-a990-65e446d1ca74)

---
Now inside Visual Studio Code press F1 and run the extension command to update compile commands:
![image](https://user-images.githubusercontent.com/62588629/231914528-3808d25e-1d18-439f-82bd-e325db58460a.png)

**Comment by as3mbus** [comment]
thanks for the help some of the error are fixed, 

although there are still some error around my projects

![image](https://github.com/boocs/unreal-clangd/assets/16043293/2ed111eb-e33d-4e13-aa04-b968a5d140d7)
![image](https://github.com/boocs/unreal-clangd/assets/16043293/5594f83f-17bd-4628-96e9-27d0b37f217f)

**Comment by as3mbus** [comment]
nevermind my previous comment. 

 after twiddling and building and run the unreal the error are cleared

**Comment by boocs** [comment]
Awesome, good to  hear.

I'll be sure to update my docs to let other Windows users know about this. Thanks for the report!

**Comment by boocs** [comment]
Oh and in case you want to try 5.3,  I also tested it and it wants to use Build Tools 2022 v14.36, not the latest version which is v14.37.

**Comment by as3mbus** [comment]
okay thank you for the information. 

additionally is there a way to inform the plugin to build/generate the header file? 

I just discovered that my previously reported problem which I previously took back, requires me to build the project to fix it. 

am I missing some step in my installation, or is it supposed to work this way?

**Comment by boocs** [comment]
Yeah, it's a known issue. Any time you add a line, in a header file, above the Generated Body line you'll have to Build again. 

Is that what you were talking about?

**Comment by as3mbus** [comment]
yeah. thanks a lot for the help
